branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: date
  branch: null
  default_platform: Python 3.6
  default_region: ap-northeast-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  workspace_type: Application
