# Generated by Django 2.2.2 on 2019-06-24 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cls_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('test', models.BooleanField(default=False)),
                ('date', models.DateField(verbose_name='my_date')),
                ('cls_t', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type', to='check.cls')),
            ],
        ),
    ]
