# Generated by Django 2.2.2 on 2019-06-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='test',
        ),
        migrations.AddField(
            model_name='student',
            name='test',
            field=models.ManyToManyField(to='check.Test'),
        ),
    ]
