# Generated by Django 2.2.2 on 2019-06-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_auto_20190625_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
