# Generated by Django 2.2.2 on 2019-06-25 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0003_test_test_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='test',
        ),
    ]
