# Generated by Django 2.2.2 on 2019-06-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0005_auto_20190625_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='test',
            field=models.ManyToManyField(related_name='test', to='check.Test'),
        ),
    ]
