# Generated by Django 2.2.2 on 2019-06-25 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0007_auto_20190625_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cls_t',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type', to='check.cls'),
        ),
        migrations.AlterField(
            model_name='student',
            name='test',
            field=models.ManyToManyField(blank=True, related_name='test', to='check.Test'),
        ),
    ]
