# Generated by Django 2.2.2 on 2019-06-25 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0009_auto_20190625_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cls_t',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type', to='check.cls'),
        ),
    ]
